# Linear Regression 구현 without Pytorch, Tensorflow

# 0. 라이브러리 

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. 데이터 준비

In [36]:
x_train = np.array([[2,3,1],
                    [4,8,9],
                    [6,2,7],
                    [8,4,6]])

In [37]:
y_train = np.array([[3],[7],[5],[8]])

In [38]:
y_train

array([[3],
       [7],
       [5],
       [8]])

In [39]:
n_samples = x_train.shape[0]

In [40]:
n_features = x_train.shape[1]

In [41]:
n_features

3

# 2. 가설함수 설정
 - f(x) = w1x1+w2x2+w3x3+b

In [42]:
W = np.ones((3,1)) #1로 초기화한 weight parameters

In [43]:
b = np.ones((1,1))

 - 

In [44]:
def f(X):
  #return X[0]*W[0] + X[1]*W[1] + X[2]*W[2] + b
  return np.matmul(X, W) + b

In [49]:
y_pred = f(x_train)

# 3. Cost함수 정의

In [58]:
def loss_function(y_pred, y_train):
  n_samples = y_train.shape[0]
  deviation = y_pred - y_train
  deviation_squred = deviation**2
  #print(deviation_squred)
  loss = (1/n_samples) * deviation_squred.sum()

  return loss



In [59]:
loss_function(y_pred, y_train)

120.75

In [53]:
y_train.shape[0]

4

In [56]:
y_pred

array([[ 7.],
       [22.],
       [16.],
       [19.]])

In [57]:
y_train

array([[3],
       [7],
       [5],
       [8]])

In [61]:
def gradient(x_train, y_train, y_pred):
  n_samples = y_train.shape[0]
  dw = (1/n_samples) * np.matmul(x_train.transpose(), (y_pred-y_train))
  print(dw)

  return dw



In [69]:
def gradient_descent(W, learning_rate, dw):
  W = W - learning_rate*dw
  print(W)

In [70]:
dw = gradient(x_train, y_train, y_pred)

[[55.5]
 [49.5]
 [70.5]]


In [71]:
gradient_descent(0.01, W, dw)

[[-55.49]
 [-49.49]
 [-70.49]]


In [72]:
W

array([[1.],
       [1.],
       [1.]])

In [73]:
losses = []
for num_iter in range(100):
  #print("x_train:", x_train)
  y_pred = f(x_train)
  loss = loss_function(y_pred, y_train)
  losses.append(loss)

  dw = gradient(x_train, y_train, y_pred)
  W = gradient_descent(0.01, W, dw)

  print(W)
  print(loss)
  

[[55.5]
 [49.5]
 [70.5]]
[[-55.49]
 [-49.49]
 [-70.49]]
None
120.75


ValueError: ignored