# Neural Network with Quadratic Data
출처: https://github.com/GunhoChoi/PyTorch-FastCampus/blob/master/02_Regression%26NN/1_NN_code/1d_data/0_neural_quadratic.ipynb
- y = 8x^2+7x+3
- 4 hidden layers

<img src="./quadratic.png">

사진출처: http://cs.franklin.edu/~sieberth/MATH160/bookFiles/Chapter3/333371_0307_317-323.pdf 

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
# from visdom import Visdom
# viz = Visdom()

## 2. Data Generation

In [7]:
num_data = 1000
num_epoch = 50000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

x = init.uniform(torch.Tensor(num_data,1),-15,15)
y = (x**2) + 3 

y_noise = y + noise

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [ ]:
# visualize data

input_data = torch.cat([x,y_noise],1)

# win=viz.scatter(
#     X = input_data,
#     opts=dict(
#         xtickmin=-15,
#         xtickmax=15,
#         xtickstep=1,
#         ytickmin=0,
#         ytickmax=500,
#         ytickstep=1,
#         markersymbol='dot',
#         markercolor=np.random.randint(0, 255, num_data),
#         markersize=5,
#     ),
# )


In [ ]:

# win=viz.scatter(
#     X = torch.cat([x,y],1),
#     opts=dict(
#         xtickmin=-15,
#         xtickmax=15,
#         xtickstep=1,
#         ytickmin=0,
#         ytickmax=500,
#         ytickstep=1,
#         markersymbol='dot',
#         markercolor=np.random.randint(0, 255, num_data),
#         markersize=5,
#     ),
# )


## 3. Model & Optimizer

In [ ]:
# fully connected model with 4 hidden layer

model = nn.Sequential(
        nn.Linear(1,5),
        nn.ReLU(),
        nn.Linear(5,50),
        nn.ReLU(),
        nn.Linear(50,100),
        nn.ReLU(),
        nn.Linear(100,200),
        nn.ReLU(),
        nn.Linear(200,1)
    )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [ ]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)

    loss = loss_func(output,label)
    loss.backward() #여기서 W와 b의 미분값을 구합니다.
    optimizer.step() #구해진 미분값을 기준으로 W와 b값을 업데이트 합니다.
    
    if i % 100 ==0:
        print(loss)
    
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(76.7966, grad_fn=<L1LossBackward0>)
tensor(76.1049, grad_fn=<L1LossBackward0>)
tensor(73.8197, grad_fn=<L1LossBackward0>)
tensor(40.1578, grad_fn=<L1LossBackward0>)
tensor(19.7690, grad_fn=<L1LossBackward0>)
tensor(18.0859, grad_fn=<L1LossBackward0>)
tensor(16.3259, grad_fn=<L1LossBackward0>)
tensor(14.1524, grad_fn=<L1LossBackward0>)
tensor(11.5759, grad_fn=<L1LossBackward0>)
tensor(8.8781, grad_fn=<L1LossBackward0>)
tensor(9.2039, grad_fn=<L1LossBackward0>)
tensor(8.4262, grad_fn=<L1LossBackward0>)
tensor(8.8338, grad_fn=<L1LossBackward0>)
tensor(8.2909, grad_fn=<L1LossBackward0>)
tensor(7.8829, grad_fn=<L1LossBackward0>)
tensor(8.0622, grad_fn=<L1LossBackward0>)
tensor(8.0651, grad_fn=<L1LossBackward0>)
tensor(7.5273, grad_fn=<L1LossBackward0>)
tensor(7.1562, grad_fn=<L1LossBackward0>)
tensor(7.4477, grad_fn=<L1LossBackward0>)
tensor(7.3513, grad_fn=<L1LossBackward0>)
tensor(7.2129, grad_fn=<L1LossBackward0>)
tensor(7.0959, grad_fn=<L1LossBackward0>)
tensor(6.9771, grad_fn=<L

In [ ]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 0.1717],
        [-2.3292],
        [-0.2518],
        [ 1.6951],
        [ 0.8223]], requires_grad=True), Parameter containing:
tensor([ 0.5102, -3.5284,  3.7483, -4.5625, -0.6415], requires_grad=True), Parameter containing:
tensor([[ 2.6692e-01,  6.5333e-03, -1.3313e-01, -1.7035e-01,  2.0523e-01],
        [-2.8821e-01,  8.3312e-01, -1.0362e+00,  4.3248e-01, -4.4455e-01],
        [ 1.7936e-01,  2.9738e-01, -7.5303e-01,  7.4859e-01,  1.1144e-01],
        [-1.4474e-01, -4.4061e-01,  2.3403e-01, -3.1987e-01, -5.0107e-01],
        [-3.8502e-01,  5.4657e-02, -6.7984e-02,  2.7290e-01, -4.1729e-01],
        [-3.9104e-01,  1.2833e-02,  1.4324e-01, -1.8757e-01,  3.8878e-01],
        [-3.7666e-01,  5.9125e-03, -7.4133e-02, -4.7283e-02,  9.1362e-03],
        [-3.5463e-01,  1.7014e-01,  1.7599e-01, -3.5568e-01,  6.2610e-03],
        [ 3.1511e-01,  1.1984e-01, -2.2928e-02, -1.0929e-01,  1.1635e-01],
        [-9.3635e-02, -1.1947e-01,  4.1527e-01,  1.8281e-03, -2.45

## 5. Visualize Trained Output

In [ ]:
# win2=viz.scatter(
#     X = torch.cat([x, output],1),
#     opts=dict(
#         xtickmin=-15,
#         xtickmax=10,
#         xtickstep=1,
#         ytickmin=0,
#         ytickmax=500,
#         ytickstep=1,
#         markersymbol='dot',
#         markercolor=np.random.randint(0, 255, num_data),
#         markersize=5,
#     ),
# )


## 6. Visualize Loss Graph

In [ ]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

# win3=viz.line(
#     X = x,
#     Y = loss_data,
# )