# Neural Network with Cubic Data (multi-dimensional)
- y = x^3 -3x^2 -9x -1
- 5 hidden layers

## 1.Import Required Libraries

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
# from visdom import Visdom
# viz = Visdom()

## 2. Data Generation

In [ ]:
num_data = 1000
num_epoch = 5000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = (x**3) - 3*(x**2) - 9*x - 1

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

y_noise = y + noise

/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  after removing the cwd from sys.path.
/Users/lim/anaconda3/envs/NLPApps/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  import sys


In [ ]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

In [ ]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

## 3. Model & Optimizer

In [ ]:


model = nn.Sequential(
            nn.Linear(1,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [ ]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    output = model(x)
    optimizer.zero_grad()

    loss = loss_func(output,label)
    loss.backward()
    
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
        
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(208.7360, grad_fn=<L1LossBackward>)
tensor(208.4341, grad_fn=<L1LossBackward>)
tensor(207.6888, grad_fn=<L1LossBackward>)
tensor(204.9050, grad_fn=<L1LossBackward>)
tensor(179.3635, grad_fn=<L1LossBackward>)
tensor(131.9337, grad_fn=<L1LossBackward>)
tensor(129.3835, grad_fn=<L1LossBackward>)
tensor(126.4591, grad_fn=<L1LossBackward>)
tensor(122.7979, grad_fn=<L1LossBackward>)
tensor(117.9157, grad_fn=<L1LossBackward>)
tensor(109.7331, grad_fn=<L1LossBackward>)
tensor(97.5420, grad_fn=<L1LossBackward>)
tensor(83.6747, grad_fn=<L1LossBackward>)
tensor(92.4683, grad_fn=<L1LossBackward>)
tensor(95.2579, grad_fn=<L1LossBackward>)
tensor(83.7875, grad_fn=<L1LossBackward>)
tensor(90.0640, grad_fn=<L1LossBackward>)
tensor(87.8785, grad_fn=<L1LossBackward>)
tensor(80.0949, grad_fn=<L1LossBackward>)
tensor(85.9687, grad_fn=<L1LossBackward>)
tensor(78.0256, grad_fn=<L1LossBackward>)
tensor(83.8751, grad_fn=<L1LossBackward>)
tensor(79.4116, grad_fn=<L1LossBackward>)
tensor(84.2814, grad_fn

In [ ]:
param_list = list(model.parameters())
print(param_list)



[Parameter containing:
tensor([[ 0.4540],
        [ 1.0252],
        [-0.5678],
        [ 0.2287],
        [ 0.6094],
        [-0.7664],
        [-1.0896],
        [-1.1309],
        [ 0.6947],
        [-0.3824],
        [ 0.9449],
        [ 0.7942],
        [-1.0012],
        [-0.6286],
        [ 0.5754],
        [-0.9163],
        [ 0.0274],
        [ 0.7330],
        [-0.0401],
        [-0.6313]], requires_grad=True), Parameter containing:
tensor([-1.3936,  0.4838, -3.2044,  1.9319, -1.2221, -4.3261, -4.2213, -2.3490,
         0.3218, -2.1195,  0.1188, -0.0459, -1.4427, -0.5137, -1.9262, -5.1691,
        -0.2698,  0.6586, -0.9154, -2.4413], requires_grad=True), Parameter containing:
tensor([[ 0.1854,  0.1256,  0.2825, -0.2115,  0.1148,  0.1050,  0.2049,  0.2290,
          0.0255,  0.0030, -0.0127, -0.0342,  0.4097,  0.3419, -0.1010,  0.1530,
          0.0666, -0.0884,  0.0188,  0.0036],
        [ 0.1388,  0.1148,  0.8004, -0.7498, -0.0662,  1.0421,  0.7909,  0.3913,
          0.0959

## 5. Visualize Trained Output

In [ ]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)



## 6. Visualize Loss Graph

In [ ]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data, 
)